# Generated by Django 3.2.5 on 2021-07-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchentries',
            name='search_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchentries',
            name='search_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchentries',
            name='query_date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='searchentries',
            name='search_query',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='searchentries',
            name='user_agent',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='searchentries',
            name='user_host',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='searchentries',
            name='user_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='searchentries',
            name='user_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
