# Generated by Django 3.2.5 on 2021-07-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0002_auto_20210704_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchentries',
            name='search_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchentries',
            name='search_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
