# Generated by Django 3.2.5 on 2021-07-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0003_auto_20210704_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchentries',
            name='user_agent',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='searchentries',
            name='user_host',
            field=models.CharField(default='', max_length=50),
        ),
    ]
