# Generated by Django 3.2.5 on 2021-07-04 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0004_auto_20210704_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchentries',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='searchentries',
            name='user_name',
        ),
    ]
